# Created by trellis-cli vcanary
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  bluewater.ponorez.site:
    site_hosts:
    - canonical: bluewater.ponorez.site
      redirects: []
    local_path: ../site
    branch: master
    repo: git@github.com:example/example.com.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
